In [1]:
# Import dependencies
import pandas as pd
import numpy as np
pd.set_option('max_colwidth', 400)

### Extract the Hospital.csv Data

In [2]:
# Read the data into a Pandas DataFrame
Hospital_info_df = pd.read_csv('Data/Hospitals.csv')
Hospital_info_df.head()

,X,Y,OBJECTID,ID,NAME,ADDRESS,CITY,STATE,ZIP,ZIP4,...,VAL_DATE,WEBSITE,STATE_ID,ALT_NAME,ST_FIPS,OWNER,TTL_STAFF,BEDS,TRAUMA,HELIPAD
0,-94.945477,29.747620,8497,76777520,HOUSTON METHODIST SAN JACINTO HOSPITAL ALEXANDER CAMPUS,1700 JAMES BOWIE DRIVE,BAYTOWN,TX,77520,NOT AVAILABLE,...,2017-12-18T00:00:00.000Z,http://www.houstonmethodist.org/locations/san-jacinto-baytown/,NOT AVAILABLE,NOT AVAILABLE,48.0,NON-PROFIT,-999.0,182.0,NOT AVAILABLE,Y
1,-82.881843,40.027143,8498,129043230,"WOODS AT PARKSIDE,THE",349 OLDE RIDENOUR ROAD,COLUMBUS,OH,43230,NOT AVAILABLE,...,2018-04-26T00:00:00.000Z,http://www.thewoodsatparkside.com/,1815,NOT AVAILABLE,39.0,PROPRIETARY,-999.0,50.0,NOT AVAILABLE,NOT AVAILABLE
2,-84.168027,39.774242,8499,130045404,DAYTON CHILDREN'S HOSPITAL,ONE CHILDRENS PLAZA,DAYTON,OH,45404,NOT AVAILABLE,...,2018-04-26T00:00:00.000Z,http://www.childrensdayton.org/cms/home/index.html,1411,NOT AVAILABLE,39.0,NON-PROFIT,-999.0,155.0,PEDIATRIC LEVEL II,Y
3,-80.632972,41.005169,8500,128844512,VIBRA HOSPITAL OF MAHONING VALLEY,8049 SOUTH AVENUE,BOARDMAN,OH,44512,NOT AVAILABLE,...,2018-04-26T00:00:00.000Z,http://www.mahoningvalleyhospital.com/,1428,MAHONING VALLEY HOSPITAL BOARDMAN CAMPUS,39.0,PROPRIETARY,-999.0,45.0,NOT AVAILABLE,NOT AVAILABLE
4,-84.199398,39.747740,8501,129845417,HAVEN BEHAVIORAL SENIOR CARE OF DAYTON,"ONE ELIZABETH PLACE,E3 SUITE A",DAYTON,OH,45417,NOT AVAILABLE,...,2018-04-26T00:00:00.000Z,https://dayton.havenbehavioral.com/,1506,NOT AVAILABLE,39.0,PROPRIETARY,-999.0,32.0,NOT AVAILABLE,NOT AVAILABLE

In [3]:
# Rename the name columns.
Hospital_info_df = Hospital_info_df.rename(columns={'NAME': 'Hospital'})
Hospital_info_df.head()

,X,Y,OBJECTID,ID,Hospital,ADDRESS,CITY,STATE,ZIP,ZIP4,...,VAL_DATE,WEBSITE,STATE_ID,ALT_NAME,ST_FIPS,OWNER,TTL_STAFF,BEDS,TRAUMA,HELIPAD
0,-94.945477,29.747620,8497,76777520,HOUSTON METHODIST SAN JACINTO HOSPITAL ALEXANDER CAMPUS,1700 JAMES BOWIE DRIVE,BAYTOWN,TX,77520,NOT AVAILABLE,...,2017-12-18T00:00:00.000Z,http://www.houstonmethodist.org/locations/san-jacinto-baytown/,NOT AVAILABLE,NOT AVAILABLE,48.0,NON-PROFIT,-999.0,182.0,NOT AVAILABLE,Y
1,-82.881843,40.027143,8498,129043230,"WOODS AT PARKSIDE,THE",349 OLDE RIDENOUR ROAD,COLUMBUS,OH,43230,NOT AVAILABLE,...,2018-04-26T00:00:00.000Z,http://www.thewoodsatparkside.com/,1815,NOT AVAILABLE,39.0,PROPRIETARY,-999.0,50.0,NOT AVAILABLE,NOT AVAILABLE
2,-84.168027,39.774242,8499,130045404,DAYTON CHILDREN'S HOSPITAL,ONE CHILDRENS PLAZA,DAYTON,OH,45404,NOT AVAILABLE,...,2018-04-26T00:00:00.000Z,http://www.childrensdayton.org/cms/home/index.html,1411,NOT AVAILABLE,39.0,NON-PROFIT,-999.0,155.0,PEDIATRIC LEVEL II,Y
3,-80.632972,41.005169,8500,128844512,VIBRA HOSPITAL OF MAHONING VALLEY,8049 SOUTH AVENUE,BOARDMAN,OH,44512,NOT AVAILABLE,...,2018-04-26T00:00:00.000Z,http://www.mahoningvalleyhospital.com/,1428,MAHONING VALLEY HOSPITAL BOARDMAN CAMPUS,39.0,PROPRIETARY,-999.0,45.0,NOT AVAILABLE,NOT AVAILABLE
4,-84.199398,39.747740,8501,129845417,HAVEN BEHAVIORAL SENIOR CARE OF DAYTON,"ONE ELIZABETH PLACE,E3 SUITE A",DAYTON,OH,45417,NOT AVAILABLE,...,2018-04-26T00:00:00.000Z,https://dayton.havenbehavioral.com/,1506,NOT AVAILABLE,39.0,PROPRIETARY,-999.0,32.0,NOT AVAILABLE,NOT AVAILABLE

In [4]:
# Get a brief summary 
Hospital_info_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7570 entries, 0 to 7569
Data columns (total 34 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   X           7570 non-null   float64
 1   Y           7570 non-null   float64
 2   OBJECTID    7570 non-null   int64
 3   ID          7570 non-null   int64
 4   Hospital    7570 non-null   object
 5   ADDRESS     7570 non-null   object
 6   CITY        7570 non-null   object
 7   STATE       7570 non-null   object
 8   ZIP         7570 non-null   int64
 9   ZIP4        7570 non-null   object
 10  TELEPHONE   7570 non-null   object
 11  TYPE        7570 non-null   object
 12  STATUS      7570 non-null   object
 13  POPULATION  7570 non-null   int64
 14  COUNTY      7570 non-null   object
 15  COUNTYFIPS  7570 non-null   object
 16  COUNTRY     7570 non-null   object
 17  LATITUDE    7570 non-null   float64
 18  LONGITUDE   7570 non-null   float64
 19  NAICS_CODE  7570 non-null   int64
 20  NAICS_DESC  7570 non-null   object
 21  SOURCE      7570 non-null   object
 22  SOURCEDATE  7570 non-null   object
 23  VAL_METHOD  7570 non-null   object
 24  VAL_DATE    7570 non-null   object
 25  WEBSITE     7570 non-null   object
 26  STATE_ID    7570 non-null   object
 27  ALT_NAME    7569 non-null   object
 28  ST_FIPS     7569 non-null   float64
 29  OWNER       7569 non-null   object
 30  TTL_STAFF   7569 non-null   float64
 31  BEDS        7569 non-null   float64
 32  TRAUMA      7569 non-null   object
 33  HELIPAD     7569 non-null   object
dtypes: float64(7), int64(5), object(22)
memory usage: 2.0+ MB

In [5]:
# Get the columns.
Hospital_info_df.columns

Index(['X', 'Y', 'OBJECTID', 'ID', 'Hospital', 'ADDRESS', 'CITY', 'STATE',
       'ZIP', 'ZIP4', 'TELEPHONE', 'TYPE', 'STATUS', 'POPULATION', 'COUNTY',
       'COUNTYFIPS', 'COUNTRY', 'LATITUDE', 'LONGITUDE', 'NAICS_CODE',
       'NAICS_DESC', 'SOURCE', 'SOURCEDATE', 'VAL_METHOD', 'VAL_DATE',
       'WEBSITE', 'STATE_ID', 'ALT_NAME', 'ST_FIPS', 'OWNER', 'TTL_STAFF',
       'BEDS', 'TRAUMA', 'HELIPAD'],
      dtype='object')

### Extract the children_hospitals.csv data

In [6]:
# Read the data into a Pandas DataFrame
children_hospital_info_df = pd.read_csv('Data/childrens_hospitals.csv')
children_hospital_info_df.head()

,Hospital,Alternative Name,Address,Address 1,Address 2,City,State,Zip,Hospital Website,Latitude,...,Affiliation,Beds,Regular Beds,NICU Beds,Opened,Pediatric Trauma Level,NICU Level,Ranked Specialties,Wikipedia Source,Magnet Designation
0,Children's Hospital of Nevada,NaN,"800 Hope Pl, Las Vegas, NV 89106",800 Hope Pl,NaN,Las Vegas,LA,89106,http://www.chnv.org/,36.160937,...,NaN,77.0,NaN,NaN,NaN,Level II Pediatric,3.0,NaN,https://en.wikipedia.org/w/index.php?title=AnMed_Health_Women%27s_and_Children%27s_Hospital&action=edit&redlink=1,NaN
1,Phoenix Children's Hospital,NaN,"1919 E. Thomas Rd., Phoenix, AZ 85016",1919 E. Thomas Rd.,NaN,Phoenix,AZ,85016,http://www.phoenixchildrens.org/,33.478744,...,NaN,457.0,NaN,NaN,NaN,Level I Pediatric,3.0,10.0,https://en.wikipedia.org/w/index.php?title=Baystate_Children%27s_Hospital&action=edit&redlink=1,NaN
2,AnMed Health Women's and Children's Hospital,NaN,"2000 E Greenville St, Anderson, SC 29621",2000 E Greenville St,NaN,Anderson,SC,29621,https://anmedhealth.org/services/womens-care,34.545556,...,NaN,72.0,NaN,NaN,NaN,NaN,NaN,NaN,https://en.wikipedia.org/w/index.php?title=Blank_Children%27s_Hospital&action=edit&redlink=1,NaN
3,Jeff Gordon's Children's Hospital,NaN,"920 Church St N, Concord, NC 28025",920 Church St N,NaN,Concord,NC,28025,https://atriumhealth.org/medical-services/childrens-services/jeff-gordon-childrens-center,35.438005,...,NaN,53.0,NaN,NaN,NaN,NaN,3.0,NaN,https://en.wikipedia.org/w/index.php?title=Bronson_Methodist_Children%27s_Health&action=edit&redlink=1,NaN
4,Levine Children's Hospital,NaN,"1000 Blythe Blvd, Charlotte, NC 28203",1000 Blythe Blvd,NaN,Charlotte,NC,28203,https://atriumhealth.org/medical-services/childrens-services/levine-childrens-hospital,35.203416,...,NaN,236.0,NaN,NaN,NaN,Level I Pediatric,3.0,8.0,https://en.wikipedia.org/w/index.php?title=CAMC_Women_and_Children%27s_Hospital&action=edit&redlink=1,NaN

In [7]:
# Get a brief summary 
children_hospital_info_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 223 entries, 0 to 222
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Hospital                223 non-null    object
 1   Alternative Name        2 non-null      object
 2   Address                 217 non-null    object
 3   Address 1               217 non-null    object
 4   Address 2               3 non-null      object
 5   City                    217 non-null    object
 6   State                   217 non-null    object
 7   Zip                     215 non-null    object
 8   Hospital Website        221 non-null    object
 9   Latitude                217 non-null    float64
 10  Longitude               217 non-null    float64
 11  Caring System           1 non-null      object
 12  Funding                 1 non-null      object
 13  Type                    1 non-null      object
 14  Affiliation             19 non-null     object
 15  Beds                    197 non-null    float64
 16  Regular Beds            1 non-null      float64
 17  NICU Beds               2 non-null      float64
 18  Opened                  2 non-null      float64
 19  Pediatric Trauma Level  109 non-null    object
 20  NICU Level              177 non-null    float64
 21  Ranked Specialties      95 non-null     float64
 22  Wikipedia Source        214 non-null    object
 23  Magnet Designation      0 non-null      float64
dtypes: float64(9), object(15)
memory usage: 41.9+ KB

In [8]:
# Get the columns.
children_hospital_info_df.columns

Index(['Hospital', 'Alternative Name', 'Address', 'Address 1', 'Address 2',
       'City', 'State', 'Zip', 'Hospital Website', 'Latitude', 'Longitude',
       'Caring System', 'Funding', 'Type', 'Affiliation', 'Beds',
       'Regular Beds', 'NICU Beds', 'Opened', 'Pediatric Trauma Level',
       'NICU Level', 'Ranked Specialties', 'Wikipedia Source',
       'Magnet Designation'],
      dtype='object')

In [9]:
children_hospital_info_df[["childrens hospital"]] = 'yes'

In [10]:
children_hospital_info_df.head()

,Hospital,Alternative Name,Address,Address 1,Address 2,City,State,Zip,Hospital Website,Latitude,...,Beds,Regular Beds,NICU Beds,Opened,Pediatric Trauma Level,NICU Level,Ranked Specialties,Wikipedia Source,Magnet Designation,childrens hospital
0,Children's Hospital of Nevada,NaN,"800 Hope Pl, Las Vegas, NV 89106",800 Hope Pl,NaN,Las Vegas,LA,89106,http://www.chnv.org/,36.160937,...,77.0,NaN,NaN,NaN,Level II Pediatric,3.0,NaN,https://en.wikipedia.org/w/index.php?title=AnMed_Health_Women%27s_and_Children%27s_Hospital&action=edit&redlink=1,NaN,yes
1,Phoenix Children's Hospital,NaN,"1919 E. Thomas Rd., Phoenix, AZ 85016",1919 E. Thomas Rd.,NaN,Phoenix,AZ,85016,http://www.phoenixchildrens.org/,33.478744,...,457.0,NaN,NaN,NaN,Level I Pediatric,3.0,10.0,https://en.wikipedia.org/w/index.php?title=Baystate_Children%27s_Hospital&action=edit&redlink=1,NaN,yes
2,AnMed Health Women's and Children's Hospital,NaN,"2000 E Greenville St, Anderson, SC 29621",2000 E Greenville St,NaN,Anderson,SC,29621,https://anmedhealth.org/services/womens-care,34.545556,...,72.0,NaN,NaN,NaN,NaN,NaN,NaN,https://en.wikipedia.org/w/index.php?title=Blank_Children%27s_Hospital&action=edit&redlink=1,NaN,yes
3,Jeff Gordon's Children's Hospital,NaN,"920 Church St N, Concord, NC 28025",920 Church St N,NaN,Concord,NC,28025,https://atriumhealth.org/medical-services/childrens-services/jeff-gordon-childrens-center,35.438005,...,53.0,NaN,NaN,NaN,NaN,3.0,NaN,https://en.wikipedia.org/w/index.php?title=Bronson_Methodist_Children%27s_Health&action=edit&redlink=1,NaN,yes
4,Levine Children's Hospital,NaN,"1000 Blythe Blvd, Charlotte, NC 28203",1000 Blythe Blvd,NaN,Charlotte,NC,28203,https://atriumhealth.org/medical-services/childrens-services/levine-childrens-hospital,35.203416,...,236.0,NaN,NaN,NaN,Level I Pediatric,3.0,8.0,https://en.wikipedia.org/w/index.php?title=CAMC_Women_and_Children%27s_Hospital&action=edit&redlink=1,NaN,yes

### Merge Data Frames together

In [11]:
Hospitals_merged_df = Hospital_info_df.merge(children_hospital_info_df, on='Hospital', how='left')

Hospitals_merged_df.tail()

,X,Y,OBJECTID,ID,Hospital,ADDRESS,CITY,STATE,ZIP,ZIP4,...,Beds,Regular Beds,NICU Beds,Opened,Pediatric Trauma Level,NICU Level,Ranked Specialties,Wikipedia Source,Magnet Designation,childrens hospital
7565,-80.701221,40.372434,8492,128243953,LIFE LINE HOSPITAL,200 SCHOOL STREET,WINTERSVILLE,OH,43953,NOT AVAILABLE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7566,-81.336345,40.401257,8493,127744621,"TEN LAKES CENTER, LLC","819 NORTH FIRST STREET,3RD FLOOR",DENNISON,OH,44621,NOT AVAILABLE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7567,-84.294586,39.331523,8494,128345040,LINDNER CENTER OF HOPE,4075 OLD WESTERN ROW ROAD,MASON,OH,45040,NOT AVAILABLE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7568,-97.283341,29.112615,8495,13879022,CUERO COMMUNITY HOSPITAL,2550 NORTH ESPLANADE STREET,CUERO,TX,79022,NOT AVAILABLE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7569,-95.359806,29.711039,8496,76677004,HARRIS HEALTH SYSTEM QUENTIN MEASE HOSPITAL,3601 NORTH MACGREGOR WAY,HOUSTON,TX,77004,NOT AVAILABLE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
# Get the columns.
Hospitals_merged_df.columns

Index(['X', 'Y', 'OBJECTID', 'ID', 'Hospital', 'ADDRESS', 'CITY', 'STATE',
       'ZIP', 'ZIP4', 'TELEPHONE', 'TYPE', 'STATUS', 'POPULATION', 'COUNTY',
       'COUNTYFIPS', 'COUNTRY', 'LATITUDE', 'LONGITUDE', 'NAICS_CODE',
       'NAICS_DESC', 'SOURCE', 'SOURCEDATE', 'VAL_METHOD', 'VAL_DATE',
       'WEBSITE', 'STATE_ID', 'ALT_NAME', 'ST_FIPS', 'OWNER', 'TTL_STAFF',
       'BEDS', 'TRAUMA', 'HELIPAD', 'Alternative Name', 'Address', 'Address 1',
       'Address 2', 'City', 'State', 'Zip', 'Hospital Website', 'Latitude',
       'Longitude', 'Caring System', 'Funding', 'Type', 'Affiliation', 'Beds',
       'Regular Beds', 'NICU Beds', 'Opened', 'Pediatric Trauma Level',
       'NICU Level', 'Ranked Specialties', 'Wikipedia Source',
       'Magnet Designation', 'childrens hospital'],
      dtype='object')

In [13]:
#Delete the unwanted columns
Hospitals_merged_df = Hospitals_merged_df.drop(columns={'X', 'Y', 'OBJECTID', 'ID', 'ZIP4', 'TELEPHONE',
       'COUNTYFIPS', 'NAICS_CODE',
       'NAICS_DESC', 'SOURCE', 'SOURCEDATE', 'VAL_METHOD', 'VAL_DATE', 'STATE_ID', 'ALT_NAME', 'ST_FIPS', 'OWNER', 'TTL_STAFF',
        'Alternative Name', 'Address', 'Address 1',
       'Address 2', 'City', 'State', 'Zip', 'Hospital Website', 'Latitude',
       'Longitude', 'Type', 'Affiliation', 'Opened',
        'Ranked Specialties', 'Wikipedia Source',
       'Magnet Designation', 'Caring System', 'Funding', 'Type', 'Affiliation', 'Beds',
       'Regular Beds', 'NICU Beds', 'Opened', 'Pediatric Trauma Level',
       'NICU Level', 'Ranked Specialties', 'Wikipedia Source',
       'Magnet Designation'})
Hospitals_merged_df.head()

,Hospital,ADDRESS,CITY,STATE,ZIP,TYPE,STATUS,POPULATION,COUNTY,COUNTRY,LATITUDE,LONGITUDE,WEBSITE,BEDS,TRAUMA,HELIPAD,childrens hospital
0,HOUSTON METHODIST SAN JACINTO HOSPITAL ALEXANDER CAMPUS,1700 JAMES BOWIE DRIVE,BAYTOWN,TX,77520,GENERAL ACUTE CARE,OPEN,182,HARRIS,USA,29.747620,-94.945477,http://www.houstonmethodist.org/locations/san-jacinto-baytown/,182.0,NOT AVAILABLE,Y,NaN
1,"WOODS AT PARKSIDE,THE",349 OLDE RIDENOUR ROAD,COLUMBUS,OH,43230,SPECIAL,OPEN,50,FRANKLIN,USA,40.027143,-82.881843,http://www.thewoodsatparkside.com/,50.0,NOT AVAILABLE,NOT AVAILABLE,NaN
2,DAYTON CHILDREN'S HOSPITAL,ONE CHILDRENS PLAZA,DAYTON,OH,45404,CHILDREN,OPEN,155,MONTGOMERY,USA,39.774242,-84.168027,http://www.childrensdayton.org/cms/home/index.html,155.0,PEDIATRIC LEVEL II,Y,NaN
3,VIBRA HOSPITAL OF MAHONING VALLEY,8049 SOUTH AVENUE,BOARDMAN,OH,44512,LONG TERM CARE,OPEN,45,MAHONING,USA,41.005169,-80.632972,http://www.mahoningvalleyhospital.com/,45.0,NOT AVAILABLE,NOT AVAILABLE,NaN
4,HAVEN BEHAVIORAL SENIOR CARE OF DAYTON,"ONE ELIZABETH PLACE,E3 SUITE A",DAYTON,OH,45417,PSYCHIATRIC,OPEN,32,MONTGOMERY,USA,39.747740,-84.199398,https://dayton.havenbehavioral.com/,32.0,NOT AVAILABLE,NOT AVAILABLE,NaN

In [14]:
Hospitals_merged_df.columns

Index(['Hospital', 'ADDRESS', 'CITY', 'STATE', 'ZIP', 'TYPE', 'STATUS',
       'POPULATION', 'COUNTY', 'COUNTRY', 'LATITUDE', 'LONGITUDE', 'WEBSITE',
       'BEDS', 'TRAUMA', 'HELIPAD', 'childrens hospital'],
      dtype='object')

In [15]:
# Rename the columns.
Hospitals_merged_df = Hospitals_merged_df.rename(columns={'Hospital': 'hospital_name', 'ADDRESS': 'address', 'CITY': 'city', 'STATE': 'state', 'ZIP': 'zip', 'TYPE': 'type', 'STATUS': 'status',
       'POPULATION': 'population', 'COUNTY': 'county', 'COUNTRY': 'country', 'LATITUDE': 'latitude', 'LONGITUDE': 'longitude', 'WEBSITE': 'website',
       'BEDS': 'beds', 'TRAUMA': 'trauma', 'HELIPAD': 'helipad'})
Hospitals_merged_df.head()

,hospital_name,address,city,state,zip,type,status,population,county,country,latitude,longitude,website,beds,trauma,helipad,childrens hospital
0,HOUSTON METHODIST SAN JACINTO HOSPITAL ALEXANDER CAMPUS,1700 JAMES BOWIE DRIVE,BAYTOWN,TX,77520,GENERAL ACUTE CARE,OPEN,182,HARRIS,USA,29.747620,-94.945477,http://www.houstonmethodist.org/locations/san-jacinto-baytown/,182.0,NOT AVAILABLE,Y,NaN
1,"WOODS AT PARKSIDE,THE",349 OLDE RIDENOUR ROAD,COLUMBUS,OH,43230,SPECIAL,OPEN,50,FRANKLIN,USA,40.027143,-82.881843,http://www.thewoodsatparkside.com/,50.0,NOT AVAILABLE,NOT AVAILABLE,NaN
2,DAYTON CHILDREN'S HOSPITAL,ONE CHILDRENS PLAZA,DAYTON,OH,45404,CHILDREN,OPEN,155,MONTGOMERY,USA,39.774242,-84.168027,http://www.childrensdayton.org/cms/home/index.html,155.0,PEDIATRIC LEVEL II,Y,NaN
3,VIBRA HOSPITAL OF MAHONING VALLEY,8049 SOUTH AVENUE,BOARDMAN,OH,44512,LONG TERM CARE,OPEN,45,MAHONING,USA,41.005169,-80.632972,http://www.mahoningvalleyhospital.com/,45.0,NOT AVAILABLE,NOT AVAILABLE,NaN
4,HAVEN BEHAVIORAL SENIOR CARE OF DAYTON,"ONE ELIZABETH PLACE,E3 SUITE A",DAYTON,OH,45417,PSYCHIATRIC,OPEN,32,MONTGOMERY,USA,39.747740,-84.199398,https://dayton.havenbehavioral.com/,32.0,NOT AVAILABLE,NOT AVAILABLE,NaN

In [16]:
Hospitals_merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7570 entries, 0 to 7569
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   hospital_name       7570 non-null   object
 1   address             7570 non-null   object
 2   city                7570 non-null   object
 3   state               7570 non-null   object
 4   zip                 7570 non-null   int64
 5   type                7570 non-null   object
 6   status              7570 non-null   object
 7   population          7570 non-null   int64
 8   county              7570 non-null   object
 9   country             7570 non-null   object
 10  latitude            7570 non-null   float64
 11  longitude           7570 non-null   float64
 12  website             7570 non-null   object
 13  beds                7569 non-null   float64
 14  trauma              7569 non-null   object
 15  helipad             7569 non-null   object
 16  childrens hospital  0 non-null      object
dtypes: float64(3), int64(2), object(12)
memory usage: 1.0+ MB

In [20]:
# Convert the goal and pledged columns to a `float` data type.
Hospitals_merged_df[['hospital_name','address', 'city','state','type','status','county', 'country','website','trauma', 'helipad', 'childrens hospital'
]] = Hospitals_merged_df[['hospital_name','address', 'city','state','type','status','county', 'country','website','trauma', 'helipad', 'childrens hospital'
]].astype(str)
Hospitals_merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7570 entries, 0 to 7569
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   hospital_name       7570 non-null   object
 1   address             7570 non-null   object
 2   city                7570 non-null   object
 3   state               7570 non-null   object
 4   zip                 7570 non-null   int64
 5   type                7570 non-null   object
 6   status              7570 non-null   object
 7   population          7570 non-null   int64
 8   county              7570 non-null   object
 9   country             7570 non-null   object
 10  latitude            7570 non-null   float64
 11  longitude           7570 non-null   float64
 12  website             7570 non-null   object
 13  beds                7569 non-null   float64
 14  trauma              7570 non-null   object
 15  helipad             7570 non-null   object
 16  childrens hospital  7570 non-null   object
dtypes: float64(3), int64(2), object(12)
memory usage: 1.0+ MB

In [21]:
# Check the datatypes
Hospitals_merged_df.dtypes

hospital_name          object
address                object
city                   object
state                  object
zip                     int64
type                   object
status                 object
population              int64
county                 object
country                object
latitude              float64
longitude             float64
website                object
beds                  float64
trauma                 object
helipad                object
childrens hospital     object
dtype: object

In [ ]:
# Export the DataFrame as a CSV file. 
campaign_cleaned.to_csv("Resources/campaign.csv", index=False)

### Extract the contacts.xlsx Data.

In [ ]:
# Read the data into a Pandas DataFrame. Use the `header=2` parameter when reading in the data.
contact_info_df = pd.read_excel('Resources/contacts.xlsx', header=3)
contact_info_df.head()

### Create the Contacts DataFrame 
---
**Create a Contacts DataFrame that has the following columns:**
- A column named "contact_id"  that contains the unique number of the contact person.
- A column named "first_name" that contains the first name of the contact person.
- A column named "last_name" that contains the first name of the contact person.
- A column named "email" that contains the email address of the contact person

Then export the DataFrame as a `contacts.csv` CSV file.

### Option 1: Use Pandas to create the contacts DataFrame.

In [ ]:
# Iterate through the contact_info_df and convert each row to a dictionary.
import json
dict_values = []
for i, row in contact_info_df.iterrows():
    data = row['contact_info']
    converted_data = json.loads(data)
    row_values = [v for k, v in converted_data.items()]
    dict_values.append(row_values)


# Print out the list of values for each row.
print(dict_values)

In [ ]:
# Create a contact_info DataFrame and add each list of values, i.e., each row 
# to the 'contact_id', 'name', 'email' columns.
contacts_df = pd.DataFrame(dict_values, columns=['contact_id', 'name', 'email'])
contacts_df.head()

In [ ]:
# Check the datatypes.
contacts_df.info()

In [ ]:
# Create a "first"name" and "last_name" column with the first and last names from the "name" column. 
contacts_df[["first_name","last_name"]] = contacts_df["name"].str.split(' ', n=1, expand=True)

# Drop the contact_name column
contacts_df_clean = contacts_df.drop(['name'], axis=1)
contacts_df_clean.head()

In [ ]:
# Reorder the columns
contacts_df_clean = contacts_df_clean[['contact_id','first_name', 'last_name', 'email']]
contacts_df_clean.head()

In [ ]:
# Check the datatypes one more time before exporting as CSV file.
contacts_df_clean.info()

In [ ]:
# Export the DataFrame as a CSV file. 
contacts_df_clean.to_csv("Resources/contacts.csv", encoding='utf8', index=False)

### Option 2: Use regex to create the contacts DataFrame.

In [ ]:
contact_info_df_copy = contact_info_df.copy()
contact_info_df_copy.head()

In [ ]:
# Extract the four-digit contact ID number.
contact_info_df_copy['contact_id'] = contact_info_df_copy['contact_info'].str.extract(r'(\d{4})')
contact_info_df_copy.head()

In [ ]:
# Check the datatypes.
contact_info_df_copy.info()

In [ ]:
# Convert the "contact_id" column to an int64 data type.
contact_info_df_copy['contact_id'] = pd.to_numeric(contact_info_df_copy['contact_id'])
contact_info_df_copy.info()

In [ ]:
# Extract the name of the contact and add it to a new column.
contact_info_df_copy['name'] = contact_info_df_copy['contact_info'].str.extract(r'([^nameil"\s][A-Za-z]+\s+[A-Za-z]+)')
contact_info_df_copy.head()

In [ ]:
# Extract the email from the contacts and add the values to a new column.
contact_info_df_copy['email'] = contact_info_df_copy['contact_info'].str.extract(r'"(\S+@\S+)"}')
contact_info_df_copy.head()

In [ ]:
# Create a copy of the contact_info_df with the 'contact_id', 'name', 'email' columns.
contacts_df_copy2 = contact_info_df_copy[['contact_id', 'name', 'email']].copy()
contacts_df_copy2.head()

In [ ]:
# Create a "first"name" and "last_name" column with the first and last names from the "name" column. 
contacts_df_copy2[["first_name","last_name"]] = contacts_df_copy2["name"].str.split(' ', n=1, expand=True)

# Drop the contact_name column
contacts_df_clean2 = contacts_df_copy2.drop(['name'], axis=1)
contacts_df_clean2.head()

In [ ]:
# Reorder the columns
contacts_df_clean2 = contacts_df_clean2[['contact_id','first_name', 'last_name', 'email']]
contacts_df_clean2.head()

In [ ]:
# Check the datatypes one more time before exporting as CSV file.
contacts_df_clean2.info()

In [ ]:
# Export the DataFrame as a CSV file. 
contacts_df_clean.to_csv("Resources/contacts.csv", encoding='utf8', index=False)